apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'cogitator-qa'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'qa'
  source:
    path: 'charts/cogitator'
    repoURL: 'https://github.com/your-org/gitops-config-repo'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-qa.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true


